modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="buddycardsapi"
version="0.1.6"
displayName="BuddycardsAPI"
authors="Pagan"
description='''
This is an API mod for developers to easily create their own Buddycard Packs, Cards, Binders, and more!!
'''

[[dependencies.buddycardsapi]]
modId="forge"
mandatory=true
versionRange="[47.4.10,)"
ordering="NONE"
side="BOTH"

[[dependencies.buddycardsapi]]
modId="buddycards"
mandatory=true
versionRange="[1.20.1-4.2.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.buddycardsapi]]
modId="kubejs"
mandatory=true
versionRange="[2001.6.5,)"
ordering="AFTER"
side="BOTH"